/* Core logic to paste into a CubeMX-generated STM32F103C8T6 HAL project.
 * GPIO setup should be generated by CubeMX using the pins described in README.md.
 */

while (1)
{
    HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);

    if (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_12) == GPIO_PIN_RESET)
        HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_SET);
    else
        HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_RESET);

    if (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_13) == GPIO_PIN_RESET)
        HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_1);

    HAL_Delay(100);
}
